version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./static:/app/static
      - ./palworld_save_pal:/app/palworld_save_pal
    environment:
      - PORT=5174
    command: python psp.py

volumes:
  static: