services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./ui_build:/app/ui
      - ./data:/app/data
      - ./palworld_save_pal:/app/palworld_save_pal
    environment:
      - PORT=5174
    command: python psp.py