services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      # Change this to the URL of your public server
      - PUBLIC_WS_URL=127.0.0.1:5174/ws
    ports:
      - "5174:5174"
    volumes:
      - ./data:/app/data
      - ./palworld_save_pal:/app/palworld_save_pal
    environment:
      - PORT=5174
    command: python psp.py