on:
    release:
      types: [published]
  
jobs:
    github-releases-to-discord:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Github Releases To Discord
          uses: SethCohen/github-releases-to-discord@v1.13.1
          with:
            webhook_url: ${{ secrets.WEBHOOK_URL }}
            color: "2105893"
            username: "PSPBot"
            avatar_url: "https://raw.githubusercontent.com/oMaN-Rod/palworld-save-pal/refs/heads/main/ui/static/psp.png"
            content: "||@PSP Announcements||\nGrab the latest release:\nNexus Mods: https://www.nexusmods.com/palworld/mods/1827\nGithub: ${{ github.event.release.html_url }}"
            footer_title: "Changelog"
            footer_icon_url: "https://raw.githubusercontent.com/oMaN-Rod/palworld-save-pal/refs/heads/main/ui/static/psp.png"
            footer_timestamp: true  
